### ISSUE TITLE
Dashboard Sometimes shows Error on Refresh

### ISSUE THREAD

**Issue by fthomas-team** [M-Files/VAF.Extensions.Community#110]
![image](https://github.com/M-Files/VAF.Extensions.Community/assets/79266516/9171e306-0e9b-4fbf-a4d3-d5be1c91f7eb)

Nullable object must have a value.

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at MFiles.VAF.Extensions.TaskInformation.GetElapsedTime()
   at MFiles.VAF.Extensions.Dashboards.AsynchronousDashboardContent.DashboardTableAsynchronousExecutionsDashboardContentRenderer.GetDashboardContent(DashboardQueueAndTaskDetails details, IEnumerable`1 executions)
   at MFiles.VAF.Extensions.Dashboards.AsynchronousDashboardContent.DashboardListAsynchronousDashboardContentRenderer.GetDashboardContent(KeyValuePair`2 item)
   at MFiles.VAF.Extensions.Dashboards.AsynchronousDashboardContent.DashboardListAsynchronousDashboardContentRenderer.<GetDashboardContent>b__6_1(KeyValuePair`2 d)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at MFiles.VAF.Extensions.Dashboards.AsynchronousDashboardContent.DashboardListAsynchronousDashboardContentRenderer.GetDashboardContent(IEnumerable`1 data)
   at MFiles.VAF.Extensions.ConfigurableVaultApplicationBase`1.<GetStatusDashboardRootItems>d__40.MoveNext()

Originally reported here: https://community.m-files.com/groups-1602070992/developers/f/developer-forum/8741/task-dashboard-intermittent-error/25627#25627

**Comment by CraigHawker** [comment]
The issue looks to be here: https://github.com/M-Files/VAF.Extensions.Community/blob/8d19af07d54f04b97b58cc575afd7324408d0a76/MFiles.VAF.Extensions/TaskQueueBackgroundOperations/TaskInformation.cs#L95

It seems that this line attempts to use "this.Started.Value" without checking that it has a value.  It should only do this when the task is in progress (so I guess I assumed that it'd always have a started time), but perhaps there are some brief situations where the task can be reserved but there's no start time available.

**Comment by CraigHawker** [comment]
I have just published a prerelease to test the above fix.  If you're encountering this often, @fthomas-team, might you be able to test it?

The version is just going through validation but should be available in a few minutes: https://www.nuget.org/packages/MFiles.VAF.Extensions/23.7.0.72-issue-110
